Добавление 6 домашки
vmelfx/it_hillel_python_basic_meleshchenko pull request #1
Opened 2022-08-01 16:00 UTC by vmelfx

Добавлены все задания из 6 домашкит

2022-08-03 16:23 UTC, Ruslan-Skira requested changes

2022-08-03 16:23 UTC, Ruslan-Skira commented on Lecture_6/meleshchenko_task_n1_hw_6.py
> +# we can use "|" to perform it quickly
Need examples with pipe |,  {**kwargs, **kwargs}

2022-08-03 16:23 UTC, Ruslan-Skira commented on Lecture_6/meleshchenko_task_n1_hw_6.py
> +# we can use "|" to perform it quickly
[f, s, t, f ,f]
{}.extend(f)

2022-08-03 20:29 UTC, vmelfx commented on Lecture_6/meleshchenko_task_n1_hw_6.py
> +# we can use "|" to perform it quickly
Added requested examples.

2022-08-05 09:23 UTC, Ruslan-Skira approved these changes
Everything is ok.

2022-08-05 09:49 UTC, merged